source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Relax_Example', :exclusive => true do
  pod "Relax", :path => "../"
end

target 'Relax_Tests', :exclusive => true do
  pod "Relax", :path => "../"

  
end
